### ISSUE TITLE
column [column name] is of type jsonb but expression is of type character varying

### ISSUE THREAD

**Issue by DanSchoppe** [chanzuckerberg/aurora-data-api#3] opened 2019-10-23 22:02 UTC
I'm using the sqlalchemy ORM on a Postgres db with some `jsonb` columns. This driver works perfectly for querying data from the database, but fails on data insertion:
```
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: ERROR: column "properties" is of type jsonb but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
```

The underlying class and query:
```
class FeatureCollection(Base):
    __tablename__ = 'feature_collection'
    id = Column(Integer, primary_key=True)
    properties = Column(JSONB)
    ...
```

```
INSERT INTO feature_collection (properties) VALUES (:properties)
```

I'm able to make the equivalent insert using boto3's `execute_statement` as long as I include a `::jsonb` type cast.
```
INSERT INTO feature_collection (properties) VALUES (:properties::jsonb)
```

Not sure if there's something here that can be leveraged:
https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/dialects/postgresql/json.py

**Comment by kislyuk** [comment] 2019-10-25 20:11
Yep, I ran into the same issue trying to insert jsonb objects. I'll dig into this more when I have a moment.

**Comment by DanSchoppe** [comment] 2019-10-26 00:06
Cool, thanks for the info, kislyuk! Glad it wasn't user error :smile:

I'm only now becoming familiar with [PEP 249 -- Python Database API Specification v2.0](https://www.python.org/dev/peps/pep-0249) that you've previously linked. If I manage to sort this out for myself I'd be happy to contribute.

**Comment by kislyuk** [comment] 2019-10-30 05:24
@DanSchoppe I have released v0.1.0, which fixes the casting of JSON, JSONB, UUID, DATE, and TIMESTAMP. This is a work in progress and I will probably need to add more casting behaviors, but JSONB works for me now. Please test and see if this release fixes your issue.

**Comment by DanSchoppe** [comment] 2019-11-27 05:03
@kislyuk Unfortunately I didn't get a chance to test the new JSONB support. Would you prefer I close this issue or leave it open?

**Comment by kislyuk** [comment] 2020-10-01 22:14
Closing this for now since the original issue is no longer reproducible.

**Closed as completed by kislyuk** 2020-10-01 22:14 UTC
